# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 200e4a3f4cc774dd52bba4b4365c85ebfb0c4bfda085d313e111a8deecfa6f2aeb4921d2429251a3be7ac0bf3eeae7ef816644c51cf8505f3ef8c91770039dae

test:
  secret_key_base: 85b5f0b14b82ee73681fa6d7407ec586f6a7ff94189eca075520957d2a836b729b1accabbcdadfcf7a19129b189aaceb730b22f233266d17f5f12786afd11891

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
