# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 77bef9d60de0905aa45e424696559e66182b8f1115becad076cfbe104fb1de440faddfd5a2e07f581e5e64111f0ad34106bf2dd01b5012c3ed33b0c7f9f88cec

test:
  secret_key_base: d430dfbe959d71d97bb417cce30e098e319356d4caebe10b8839b137505c37eb614542d5b8190aff048ef8ba540941e7d6f0337af5cdedc1b1d05d1fab7c3abb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
